#!/usr/bin/env sh
set -ex

TAG="$( date -u +'%Y%m%dT%H%M%S' )"
DIRNAME=`dirname "$( realpath "$0" )"`
TAGGED_IMAGE="${1:-cloud-run-102}:${TAG}"

docker build --tag "${TAGGED_IMAGE}" "${DIRNAME}"
echo "${TAG}" > "${DIRNAME}/tag"
echo "${TAGGED_IMAGE}"
