#!/usr/bin/env sh

SERVICE="cloud-run-102"
REGION="us-central1"
DOMAIN="${SERVICE}.macrocephal.cloud"

./build
gcloud beta run deploy "${SERVICE}" --region "${REGION}" --image "gcr.io/salathielgenese-playground/${SERVICE}"

gcloud beta run domain-mappings describe --region "${REGION}" --domain cloud-run-102.macrocephal.cloud ||
    gcloud beta run domain-mappings create --service "${SERVICE}" --region "${REGION}" --domain "${DOMAIN}"
